CREATE TABLE [dbo].[Employee]
(
	Id INT NOT NULL PRIMARY KEY,
	AddressId INT NOT NULL,
	PersonId INT NOT NULL,
	CompanyName NVARCHAR(50) NOT NULL,
	Position NVARCHAR(50) NULL,
	EmployeeName NVARCHAR(100) NULL,
	FOREIGN KEY (PersonId) REFERENCES Person(Id),
	FOREIGN KEY (AddressId) REFERENCES Address(Id),
)